### ISSUE TITLE
咕咕咕...大佬加油！

### ISSUE THREAD

**Issue by sm19951010** [tubaxiaosiji/RTL8125-Driver-for-Proxmox-VE5-6-and-debian9-10#2]
小白自己下了螃蟹官网驱动到pve里貌似编译不了，据说要另外装内核什么的...加油啊大佬期待！

**Comment by tubaxiaosiji** [comment]
主要是PVE的内核命名方式有点诡异。。。我也是摸索了好久才知道，其实编译这些驱动，主要是需要下载与内核版本相对应的Linux-Headers才行。我写的这个脚本就是想自动匹配好PVE内核版本，实现一键编译。。。。Linux下字符串剪切匹配的啥我还不太会。所以一直卡在这里。。。QAQ

**Comment by tubaxiaosiji** [comment]
> 
> 
> 小白自己下了螃蟹官网驱动到pve里貌似编译不了，据说要另外装内核什么的...加油啊大佬期待！

来试试吧，看能用不

**Comment by tubaxiaosiji** [comment]
PVE 6.0下通过测试，请试试看？

**Comment by sm19951010** [comment]
> > 小白自己下了螃蟹官网驱动到pve里貌似编译不了，据说要另外装内核什么的...加油啊大佬期待！
> 
> 来试试吧，看能用不

厉害啊大佬，lsmod可以看到r8125成功装上了，刚在司波图的视频里看到介绍你的脚本才发现已经更新完工了！不过上次自己没有编译成功后换了其他网卡...有些遗憾，太强了

**Comment by tubaxiaosiji** [comment]
![image](https://user-images.githubusercontent.com/27133369/86524280-3bc9fe00-beab-11ea-9ca4-d90258cb492e.png)
